packages:
    # all packages in direct subdirs of packages/
    - packages/**
    # except playgrounds packages
    - '!playgrounds'
catalog:
    "@eslint/js": ^9.13.0
    "@stylistic/eslint-plugin": ^2.9.0
    "@types/node": ^22.8.1
    "@types/react": ^18.3.12
    "@types/react-dom": ^18.3.1
    "@vitejs/plugin-react": ^4.3.3
    autoprefixer: ^10.4.20
    eslint: ^9.13.0
    eslint-plugin-react-hooks: ^5.0.0
    eslint-plugin-react-refresh: ^0.4.14
    globals: ^15.11.0
    lint-staged: ^15.2.10   
    pnpm: ^9.12.2
    postcss: ^8.4.47
    postcss-cli: ^11.0.0
    react: ^18.3.1
    react-dom: ^18.3.1
    simple-git-hooks: ^2.11.1
    typescript: ^5.6.3
    typescript-eslint: ^8.11.0
    vite: ^5.4.10
    vite-plugin-dts: ^4.3.0
