name: 새로운 기능 제안 ✨
description: Use this template to report new features. 
labels: [enhancement]
body:
    - type: textarea
      id: description
      attributes:
          label: Describe the new feature
          description: "구현해야 하는 새로운 기능과 요구사항을 기입 부탁드립니다."
      validations:
          required: true
